- README.md
- Updating README to include blog posts for DCX React Library
> feat: adding blog posts to the README

- src/formInput/FormInput.tsx
making the value for the form input optional
will close: https://github.com/Capgemini/dcx-react-library/issues/286
> feat: make value optional

- src/button/__tests__/Button.test.tsx
resolving:
```bash
$ eslint src
/home/circleci/repo/src/button/__tests__/Button.test.tsx
201:54  error  Strings must use singlequote  quotes
```
> fix: lint issue

- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- stories/Button/Documentation.stories.mdx
- stories/liveEdit/ButtonLive.tsx
Updates the button component to have a name property
https://github.com/Capgemini/dcx-react-library/issues/314
> feat: adds name property to button component

- src/autocomplete/ResultList.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- src/autocomplete/__tests__/ResultList.test.tsx
> feat: autocomplete no results

- example/src/components/AutocompleteDemo.tsx
- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- src/formInput/FormInput.tsx
- stories/Autocomplete/Styled.stories.mdx
- stories/Autocomplete/UnStyled.stories.mdx
- stories/Autocomplete/style.css
> feat: Autocomplete prompt for minChars or promptCondition

- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- stories/Button/Documentation.stories.mdx
- stories/liveEdit/ButtonLive.tsx
You can put string or number as value in the button.
> feat: button-value

- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- stories/Button/Documentation.stories.mdx
- stories/liveEdit/ButtonLive.tsx
Reverts Capgemini/dcx-react-library#342
> Revert "feat: button-value"

- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
Please note I have raised a few questions on #334 that may be useful to consider first
> Conditionally render aria-label

- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- src/copyToClipboard/CopyToClipboard.tsx
- src/copyToClipboard/__test__/CopyToClipboard.test.tsx
- src/details/Details.tsx
- src/details/__test__/Details.test.tsx
- src/formDate/Date.tsx
- src/formDate/FormDate.tsx
- src/formDate/__test__/FormDate.test.tsx
- stories/Details/Documentation.stories.mdx
- stories/FormDate/Documentation.stories.mdx
- stories/liveEdit/DetailsLive.tsx
- stories/liveEdit/FormDateLive.tsx
Reverts Capgemini/dcx-react-library#389
> tab index part 1

- src/table/Table.tsx
- src/table/__tests__/Table.test.tsx
- stories/liveEdit/TableLive.tsx
- stories/table/Documentation.stories.mdx
Issue: https://github.com/Capgemini/dcx-react-library/issues/301
Capability to take a tabIndex that can added to the element within the DOM has been added to Table component.
> fix: table tab index

- .storybook/preview.js
- example/src/components/library-candidates/LoginForm.tsx
- example/src/pages/Register.tsx
- src/index.ts
- stories/Utils/Documentation.stories.mdx
Issue: https://github.com/Capgemini/dcx-react-library/pull/411
- documentation added to Storybook
- className util added to index.ts file to be packaged
- using className util from dcx-react-library in the example project
> classNames util documentation and using it in example project

- example/src/components/AutocompleteDemo.tsx
- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- stories/Autocomplete/Documentation-server.stories.mdx
- stories/Autocomplete/Documentation.stories.mdx
- stories/Autocomplete/Styled.stories.mdx
- stories/Autocomplete/UnStyled.stories.mdx
- stories/liveEdit/AutocompleteLive.tsx
- adding a way to sort the array of strings within a filtered list based on a provided search function passed in as a prop
example: 
```tsx
const quickSearch = (searchQuery: string, options: any[]) => {
// some user defined search and / or sort algorithm to find and order results
return ['result 1', 'result 2', 'result 3'];
}
<Autocomplete 
options={options} 
search={quickSearch} // user defined search and/ or sort function
/>
```
> feat: adding prop to specify a sort algorithm for results

- package.json
- src/characterCount/CharacterCount.tsx
- src/characterCount/__tests__/CharacterCount.test.tsx
- stories/CharacterCount/Documentation.stories.mdx
- stories/CharacterCount/Syled.stories.mdx
- stories/CharacterCount/UnStyled.stories.mdx
- stories/liveEdit/CharacterCountLive.tsx
will allow to specify a custom message
> feat: add custom message word count

- src/details/Details.tsx
- src/details/__test__/Details.test.tsx
- stories/Details/Documentation.stories.mdx
- stories/liveEdit/DetailsLive.tsx
Issue  - https://github.com/Capgemini/dcx-react-library/issues/438
> adding id prop for summary text span tag

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- stories/Autocomplete/Documentation.stories.mdx
- stories/liveEdit/AutocompleteLive.tsx
adding id prop for label and hint tag for - https://github.com/Capgemini/dcx-react-library/issues/439
> adding id prop for label and hint tag

- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- stories/Button/Documentation.mdx
- stories/liveEdit/ButtonLive.tsx
fix for this issue: https://github.com/Capgemini/dcx-react-library/issues/466
> Add new properties to the button component developer specified class name and a variant

- src/tabGroup/TabGroup.tsx
Replaced the empty JSX for a re4act fragment to add the key property
> fix: replaced empty jsx with react fragment

- stories/TabGroup/Documentation.mdx
Improves tab documentation to display correct properties
> Tab documentation fix

- src/design-system/abbreviate.css
- src/design-system/index.css
- src/design-system/tokens.json
- stories/Abbreviate/design-system/AccessibleTheme.stories.js
- stories/Abbreviate/design-system/DarkTheme.stories.js
- stories/Abbreviate/design-system/Default.stories.js
- stories/Abbreviate/design-system/MaterialTheme.stories.js
- stories/Abbreviate/design-system/Playground.stories.js
- stories/themes/accessible.theme.css
- stories/themes/dark.theme.css
- stories/themes/material.theme.css
Done!! hope all is well any suggestions are welcome👍🏼
> Abbreviate - design system
