- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- stories/Button/Documentation.stories.mdx
- stories/Button/UnStyled.stories.mdx
- stories/liveEdit/ButtonLive.tsx
please let me know if you think it is not correct, as this is my first PR 🎉
Thanks a lot.
> issue-formAction

- src/common/components/ErrorMessage.tsx
- src/common/components/__tests__/ErrorMessage.test.tsx
Hides the error element in the ErrorMessage component if the text property is not present
https://github.com/Capgemini/dcx-react-library/issues/315
> feat: hides error element if text is not present

- package.json
- src/common/components/CheckboxRadioBase.tsx
- src/common/components/Conditional.tsx
- src/formCheckbox/__test__/FormCheckbox.test.tsx
- stories/FormCheckbox/Documentation.stories.mdx
Updates the common checkbox and radio component to show the conditional when JS is off
https://github.com/Capgemini/dcx-react-library/issues/309
> fix: updates checkbox/radio to show conditional with nojs

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
> fix: On initial render, ensure that the input prompt for Autocomplete is not visible unless focused

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
> fix: [Autocomplete] Ensure the value of controlled input is never undefined

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- stories/Autocomplete/Styled.stories.mdx
- stories/style.css
- Navigation with the keyboard is already working; users just need to remember to add `resultActiveClass` to make it obvious which item is highlighted.  However, this PR adds `preventDefault()` for the `Enter` key to prevent unintentionally causing form submission when the `Autocomplete` component is part of a HTML `form` and an option is selected by pressing `Enter`.
- Improved `onBlur` functionality to ensure the results list is not displayed
Fixes #320
> fix: Autocomplete accessibility improvements

- example/src/components/FormCheckboxDemo.tsx
- example/src/components/FormRadioDemo.tsx
- example/src/pages/Register.tsx
- src/index.ts
https://github.com/Capgemini/dcx-react-library/issues/384
> Fix checkbox / radio group refactor missing from `example/src`

- src/multiUpload/MultiUpload.tsx
There is a question added to #352 relating to this PR.
> feat: move elements outside of label

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- As the `onBlur` on the text input was closing the results list, it was interrupting the click handler for the results list and this was the cause of issue #399 
- The `onBlur` on the text input no longer closes the results list, so clicking outside has no effect anymore.  However, we can now press the `Escape` key to close it.  Will need to come up with a different way of closing the results list if clicking outside
Fixes #399
> fix: allow closing of the Autocomplete results list with the Escape key instead of onBlur

- src/range/Range.tsx
- src/range/__tests__/Range.test.tsx
- stories/liveEdit/RangeLive.tsx
- stories/range/Documentation.stories.mdx
Issue: https://github.com/Capgemini/dcx-react-library/issues/301
Capability to take a tabIndex that can added to the element within the DOM has been added to Progress component.
> fix: range tabindex

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- src/formInput/FormInput.tsx
- src/formInput/__tests__/FormInput.test.tsx
- src/multiSelect/MultiSelect.tsx
- src/multiSelect/__test__/MultiSelect.test.tsx
- stories/Autocomplete/Documentation.stories.mdx
- stories/Input/Documentation.stories.mdx
- stories/MultiSelect/Documentation.stories.mdx
- stories/liveEdit/AutocompleteLive.tsx
- stories/liveEdit/FormInputLive.tsx
- stories/liveEdit/MultiSelectLive.tsx
Issue: https://github.com/Capgemini/dcx-react-library/issues/301
Capability to take a tabIndex that can added to the element within the DOM has been added to MultiSelect component.
> fix: multi select can accept tabindex

- .storybook/main.js
- package.json
- yarn.lock
Issue: https://github.com/Capgemini/dcx-react-library/issues/376
Installed webpack 5 for storybook and updated config as storybook had been using webpack 4 by default which doesn't support node v18.
> fix: installed webpack 5 for storybook to enable build with node v18

- src/formInput/FormInput.tsx
- src/formInput/__tests__/FormInput.test.tsx
- stories/Input/Styled.stories.mdx
Issue: https://github.com/Capgemini/dcx-react-library/issues/405
added `errorPosition.AFTER_HINT` option for after hint in formInput component
> fix: added error position option for after hint in formInput component

- src/autocomplete/ResultList.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- src/autocomplete/__tests__/ResultList.test.tsx
- src/common/components/__tests__/ErrorMessage.test.tsx
- src/common/utils/__tests__/classNames.tsx
- src/common/utils/classNames.ts
- src/common/utils/index.ts
- src/details/Details.tsx
- src/formDate/FormDate.tsx
- src/formDate/__test__/FormDate.test.tsx
- src/formInput/FormInput.tsx
- src/formInput/__tests__/FormInput.test.tsx
- src/formSelect/FormSelect.tsx
- src/range/Range.tsx
- src/tabGroup/TabGroup.tsx
- src/tabGroup/components/Tab.tsx
- src/table/Body.tsx
- src/toggle/Toggle.tsx
- src/tooltip/Tooltip.tsx
Issue: https://github.com/Capgemini/dcx-react-library/issues/407
- small change to classNames and conditionalClassNames: added .trim() to both
- scanned all components and replaced .join(' ') and conditionals for class names with the new classNames and conditionalClassNames util functions
- added/amended some tests where appropriate
> use classNames utils

- example/src/components/CharacterCountDemo.tsx
- package.json
- src/characterCount/CharacterCount.tsx
- src/characterCount/__tests__/CharacterCount.test.tsx
- stories/CharacterCount/Documentation.stories.mdx
Issue: https://github.com/Capgemini/dcx-react-library/issues/437
Character count is reset on focus. So after the textarea has been cleared programmatically, and then the textarea is focussed, the counter and the message will be reset to the correct value.
_This is not the perfect solution as the count and message is not updated on clicking the button that clears the form._
> fix: reset character count on focus

- example/src/index.tsx
- package.json
- src/tabGroup/TabGroup.tsx
- src/tabGroup/__test__/TabGroup.test.tsx
- src/tabGroup/components/Tab.tsx
- src/tabGroup/components/__test__/Tab.test.tsx
- Add a specific class to tab panels when JS is disabled and use the `:target` CSS pseudoclass to show and hide content
- In `Tab.tsx`, replace `id` with `data-tab-id` as this was creating duplicate IDs on the page, i.e., both the tab and the tabpanel had the same value for the `id` attribute
- Update the `example` project to use React 18's `ReactDOM.createRoot` instead of `ReactDOM.render`
> feat: Tabs are now non-js compliant

- package.json
- src/accordion/Accordion.tsx
- src/accordion/__tests__/Accordion.test.tsx
fix a minor bug that was stopping example to run correctly
> feat: fix minor bug on the accordion

- src/design-system/description-list.css
- src/design-system/index.css
- src/design-system/tokens.json
- stories/DescriptionList/design-system/AccessibleTheme.stories.js
- stories/DescriptionList/design-system/DarkTheme.stories.js
- stories/DescriptionList/design-system/Default.stories.js
- stories/DescriptionList/design-system/MaterialTheme.stories.js
- stories/DescriptionList/design-system/Playground.stories.js
- stories/themes/dark.theme.css
- stories/themes/material.theme.css
Added DescriptionList  Design System
> Description list design system

- package.json
- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
Fixes how the aria label was being rendered by the button component
https://github.com/Capgemini/dcx-react-library/issues/618
* The aria-label should default to the label if not specified as voice activation users won't know what type of button it is or that it has "-button" added afterwards.
* The aria-label attribute should always be rendered if a value is given, it doesn't make sense to hide it if the label property is being used.
> updated the button component to better render aria-label

- src/tabGroup/components/Tab.tsx
- src/tabGroup/components/__test__/Tab.test.tsx
we don't want to set tab index if it is when JS is disabled - accessibility requirement
> fix: accessbility removing tabIndex

- src/common/utils/rolesType.ts
- src/formInput/FormInput.tsx
- src/formInput/__tests__/FormInput.test.tsx
> fix: removing empty alert / error div for a formInput without an error

- example/src/components/FormInputDemo.tsx
- package.json
- src/autocomplete/Autocomplete.tsx
- src/design-system/form-input.css
- src/formInput/FormInput.tsx
- src/formInput/__tests__/FormInput.test.tsx
- stories/FormInput/ClassBased.stories.js
- stories/FormInput/Documentation.mdx
- stories/FormInput/design-system/AccessibleTheme.stories.js
- stories/FormInput/design-system/DarkTheme.stories.js
- stories/FormInput/design-system/Default.stories.js
- stories/FormInput/design-system/FloatingTheme.stories.js
- stories/FormInput/design-system/MaterialTheme.stories.js
- stories/liveEdit/FormInputLive.tsx
When rendering the form input I noticed the empty error div was still rendered on page load
```html
<div class="dcx-form-input govuk-form-group">
<label for="userReference">some label</label>
<div class="dcx-error-message"></div> 
<div class="dcx-hint govuk-hint">some hint</div>
<input name="userReference" type="text" class="govuk-input" tabindex="0" id="userReference" value="">
</div>
```
This PR remove this such that the error div containing the error message is rendered only when needed
> fix: removing unnecessary div from error message

- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- src/details/Details.tsx
- src/details/__test__/Details.test.tsx
- src/formDate/Date.tsx
- src/formDate/__test__/FormDate.test.tsx
- src/formInput/FormInput.tsx
- src/formInput/__tests__/FormInput.test.tsx
- src/formSelect/FormSelect.tsx
- src/formSelect/__test__/FormSelect.test.tsx
- src/multiSelect/MultiSelect.tsx
- src/multiSelect/__test__/MultiSelect.test.tsx
- src/progress/Progress.tsx
- src/progress/__tests__/Progress.test.tsx
- src/range/Range.tsx
- src/range/__tests__/Range.test.tsx
- src/table/Table.tsx
- src/table/__tests__/Table.test.tsx
> tabindex="0" means that the element should be focusable in sequential keyboard navigation, after any positive tabindex values. The focus navigation order of these elements is defined by their order in the document source.
We would like to ensure that all components are focus in their navigation order unless specified by the consumer.
> fix: removing the default 0 tabIndex

- CHANGELOG.md
- src/autocomplete/Autocomplete.tsx
- src/autocomplete/__tests__/Autocomplete.test.tsx
- stories/changelog.mdx
* Adds functionality where the options list will close on blur
* Moves the position of the hidden accessibility hint text so that it is not read out before the descriptive label
> adds close on blur and moves position of hidden hint text

- CHANGELOG.md
- example/src/components/ButtonDemo.tsx
- src/button/Button.tsx
- src/button/__tests__/Button.test.tsx
- stories/Button/ClassBased.stories.js
- stories/Button/Documentation.mdx
- stories/changelog.mdx
As per a GDS accessbility requirement
```tsx
<button
onClick={handleClick}
disabled={disable}
type={type}
aria-label={ariaLabel}
formAction={formAction}
name={name}
className={btnClassName}
value={value}
{...props}
>
{prefix}
{isLoading && loadingLabel ? loadingLabel : label}
{visuallyHiddenText && (
<span className={visuallyHiddenText.className}>
{visuallyHiddenText.text}
</span>
)}
{!isLoading && children}
{postfix}
</button>
```
> feat: adding visually hidden text to button for screen readers
